<a href="https://colab.research.google.com/github/NewCodeLearner/DeepLearning_PyTorch/blob/main/DailyCode_16_3_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
import torch.nn as nn

In [36]:
input = torch.tensor(torch.randn(6,6))
input = input.unsqueeze(0)
input.shape

<ipython-input-36-145b7ed8c0ce>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(torch.randn(6,6))


torch.Size([1, 6, 6])

In [42]:
input2 = input.squeeze(0)
input2.shape

torch.Size([6, 6])

In [22]:
target = torch.tensor([0.,1.,1.,0.,1.,0.])
target

tensor([0., 1., 1., 0., 1., 0.])

In [17]:
#define model class

class modelname(nn.Module):
    def __init__(self):
        super().__init__()
        self.Net = nn.Sequential(
            nn.Linear(6,10),
            nn.ReLU(),
            nn.Linear(10,1),
            nn.Sigmoid()
        )
    def forward(self,x):
        x = self.Net(x)
        return x


In [18]:
model = modelname()

In [20]:
logits = model(input)

print(logits)

tensor([[0.4575],
        [0.4181],
        [0.5040],
        [0.4345],
        [0.4975],
        [0.5063]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])


In [25]:
print(logits.squeeze().shape)
print(target.shape)

torch.Size([6])
torch.Size([6])


In [29]:
criterion = nn.BCELoss()

In [30]:
loss = criterion(logits.squeeze(),target)
print(loss)

tensor(0.6905, grad_fn=<BinaryCrossEntropyBackward0>)


In [32]:
target2 = torch.tensor([[0.],[1.],[1.],[0.],[1.],[0.]])
print(logits.shape)
print(target2.shape)

torch.Size([6, 1])
torch.Size([6, 1])


In [33]:
loss = criterion(logits.squeeze(),target)
print(loss)

tensor(0.6905, grad_fn=<BinaryCrossEntropyBackward0>)


In [48]:
print(logits.squeeze(0).shape)
print(target2.shape)

torch.Size([6, 1])
torch.Size([6, 1])


In [55]:
#training loop

epochs=10
optimizer = torch.optim.AdamW(model.parameters(),lr=0.1)

for i in range(epochs+1):
    optimizer.zero_grad()
    logits = model(input)
    loss = criterion(logits.squeeze(0),target2)
    loss.backward()
    optimizer.step()
    print (f'Epoch: {i} Loss: {loss.item()}')


Epoch: 0 Loss: 0.2350921481847763
Epoch: 1 Loss: 0.21405546367168427
Epoch: 2 Loss: 0.13907186686992645
Epoch: 3 Loss: 0.10381504148244858
Epoch: 4 Loss: 0.07883366197347641
Epoch: 5 Loss: 0.05789707601070404
Epoch: 6 Loss: 0.03835412487387657
Epoch: 7 Loss: 0.02405918575823307
Epoch: 8 Loss: 0.01405925303697586
Epoch: 9 Loss: 0.008019265718758106
Epoch: 10 Loss: 0.00454838527366519


In [57]:
print(param for param in model.parameters())

<generator object <genexpr> at 0x7e9c5d717920>


In [58]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.3096, -0.0031, -0.1512, -0.3410, -0.2397,  0.0384],
        [-1.1178,  1.6172,  1.1656,  0.1887, -0.0405, -0.1954],
        [-1.3462,  0.2270,  1.4784, -0.1079, -0.3410, -0.0376],
        [-1.3712,  1.1161,  0.5361,  1.1425, -0.6535,  0.1731],
        [-1.2164,  0.8678, -0.8803,  0.9904,  0.4788,  0.1882],
        [-0.8776, -0.0582,  0.9348,  0.4484, -0.2248,  0.1299],
        [-0.5524,  1.2666,  0.5328,  0.3320, -0.1775, -0.1870],
        [-0.7829, -0.2376,  0.5157,  0.9657, -0.6710,  0.0713],
        [ 1.1403, -1.5765, -1.1652,  1.6582, -0.4555, -1.3336],
        [ 1.1752, -0.3628,  1.1044, -0.8035,  1.6993,  0.2583]],
       requires_grad=True), Parameter containing:
tensor([-0.4266, -0.5990, -0.3552, -0.1943, -0.4166, -0.5183, -0.2872, -0.6919,
         1.2512,  0.5751], requires_grad=True), Parameter containing:
tensor([[ 0.0726, -0.3534, -1.8007, -1.6067, -1.6386, -0.7430, -1.1186, -0.5945,
          1.1204,  1.1300]], requires_grad=True), Param

In [73]:
import requests

response = requests.get('https://raw.githubusercontent.com/ilya-pimenov/LLM-Study/refs/heads/main/the-verdict.txt')
raw_text = response.text

print(len(raw_text))

20480


In [62]:
!pip install tiktoken

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 12.8 MB/s eta 0:00:00


In [74]:
import tiktoken

print(tiktoken.list_encoding_names())

tokenizer = tiktoken.get_encoding("gpt2")


['gpt2', 'r50k_base', 'p50k_base', 'p50k_edit', 'cl100k_base', 'o200k_base']


In [76]:
print(raw_text[:100])

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no g


In [77]:
tokenize_text = tokenizer.encode(raw_text)
tokenize_text[:20]

[40,
 367,
 2885,
 1464,
 1807,
 3619,
 402,
 271,
 10899,
 2138,
 257,
 7026,
 15632,
 438,
 2016,
 257,
 922,
 5891,
 1576,
 438]

In [78]:
print(tokenizer.decode(tokenize_text[10:20]))

 a cheap genius--though a good fellow enough--
