<a href="https://colab.research.google.com/github/NewCodeLearner/DeepLearning_PyTorch/blob/main/Practice_code_Coding_training_loop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch
import torch.nn as nn

In [113]:
input = torch.tensor(torch.randn(5,6))
output=torch.tensor([[0.],[1.],[1.],[0.],[1.]])
output=torch.tensor([0.,1.,1.,0.,1.])
print(input)
print(input.shape)
print(output)
print(output.shape)

tensor([[ 0.9352,  0.3702, -1.2865, -0.5216, -1.8807, -0.6477],
        [-0.5444,  0.8507, -0.0748, -0.1689, -0.5498, -0.2751],
        [ 1.7076,  0.2814, -0.0114,  1.1252,  0.3200,  1.1909],
        [-0.6162, -2.2882,  0.1140, -0.0088,  0.5143, -0.4072],
        [-1.1180, -0.1707, -1.1787,  1.2191,  1.3420,  0.1821]])
torch.Size([5, 6])
tensor([0., 1., 1., 0., 1.])
torch.Size([5])


<ipython-input-113-cc6a8ef6f8bf>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(torch.randn(5,6))


In [97]:
import torch.nn as nn

class modelname(nn.Module):
  def __init__(self):
    super().__init__()

    self.model = nn.Sequential(
        nn.Linear(6,10),
        nn.ReLU(),
        nn.Linear(10,1),
        nn.Sigmoid()
    )

  def forward(self,x):
    x=self.model(x)
    return x


In [98]:
model = modelname()

In [115]:
logits = model(input)
criterion = nn.BCELoss()
loss =criterion(logits.squeeze(),output)

print(loss.item())

0.6551779508590698


In [110]:
print(logits,output)

tensor([[0.5371],
        [0.6095],
        [0.5927],
        [0.6132],
        [0.5864]], grad_fn=<SigmoidBackward0>) tensor([[0.],
        [1.],
        [1.],
        [0.],
        [1.]])


In [91]:
for param in model.named_parameters():
  print(param)

('model.0.weight', Parameter containing:
tensor([[-0.1742,  0.1902,  0.2793,  0.2192,  0.2925,  0.3639],
        [ 0.3887,  0.0878,  0.1564,  0.2463,  0.2215,  0.0943],
        [ 0.1140, -0.1383,  0.3747,  0.0128, -0.0695, -0.3870],
        [ 0.3389,  0.1597,  0.0966, -0.1945,  0.0189,  0.1848],
        [-0.0289, -0.1729, -0.4011, -0.2921, -0.1057,  0.1604],
        [-0.0372, -0.3339, -0.3462, -0.0462, -0.1802,  0.3963],
        [-0.1620, -0.2583,  0.0932, -0.2614,  0.3690,  0.3983],
        [-0.3255,  0.3445,  0.3366,  0.3527,  0.1384, -0.2327],
        [-0.0792, -0.2066,  0.3732, -0.2702, -0.2350, -0.3152],
        [ 0.3022, -0.1362,  0.3492, -0.2830,  0.3857, -0.0867]],
       requires_grad=True))
('model.0.bias', Parameter containing:
tensor([-0.3361, -0.0476, -0.0956, -0.1359, -0.2703, -0.0620, -0.2642,  0.0365,
         0.0040,  0.3806], requires_grad=True))
('model.2.weight', Parameter containing:
tensor([[-0.2156,  0.0435,  0.1276,  0.2861, -0.0184, -0.0636,  0.0693,  0.2031,
 

In [100]:
for param in model.parameters():
  print(param.numel)

<built-in method numel of Parameter object at 0x7f0abd59dd90>
<built-in method numel of Parameter object at 0x7f0abd59e210>
<built-in method numel of Parameter object at 0x7f0abd59d850>
<built-in method numel of Parameter object at 0x7f0abd59fa10>


In [99]:
for idx, m in enumerate(model.modules()):
    print(idx, '->', m)


0 -> modelname(
  (model): Sequential(
    (0): Linear(in_features=6, out_features=10, bias=True)
    (1): ReLU()
    (2): Linear(in_features=10, out_features=1, bias=True)
    (3): Sigmoid()
  )
)
1 -> Sequential(
  (0): Linear(in_features=6, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=1, bias=True)
  (3): Sigmoid()
)
2 -> Linear(in_features=6, out_features=10, bias=True)
3 -> ReLU()
4 -> Linear(in_features=10, out_features=1, bias=True)
5 -> Sigmoid()


In [108]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [112]:
# training loop

epoch =20

for i in range(epoch):
  optimizer.zero_grad
  logits=model(input)
  loss = criterion(logits,output)
  loss.backward()
  optimizer.step()
  print(loss.item())


0.6521462202072144
0.6499055027961731
0.6469607949256897
0.6433464884757996
0.6391022801399231
0.6342476010322571
0.628655731678009
0.6225411295890808
0.6159624457359314
0.6089743971824646
0.6016255617141724
0.5939569473266602
0.5860637426376343
0.5781494975090027
0.5700382590293884
0.5616239309310913
0.5529015064239502
0.5438564419746399
0.5341852307319641
0.5239518880844116
